### ISSUE TITLE
请问大神，这个是不是要先解绑咕咕机

### ISSUE THREAD

**Issue by Shuliyey** [sherluok/memobird#2]
请问是不是要先， 解绑咕咕机， 才可以写node.js sdk 与咕咕机交流

**Comment by sherluok** [comment]
是的，你需要先按咕咕机文档指示申请成为开发者，这个开发者账号与你的咕咕机账号是绑定的。你的咕咕机账号登录的设备就是你的开发者账号操作的设备。

**Comment by sherluok** [comment]
是的，你需要先按咕咕机文档指示申请成为开发者，这个开发者账号与你的咕咕机账号是绑定的。你的咕咕机账号登录的设备就是你的开发者账号操作的设备。

**Comment by sherluok** [comment]
是的，你需要先按咕咕机文档指示申请成为开发者，这个开发者账号与你的咕咕机账号是绑定的。你的咕咕机账号登录的设备就是你的开发者账号控制的设备。
