### ISSUE TITLE
`post` function is not safe

### ISSUE THREAD

**Issue by evianzhow** [sherluok/memobird#4]
If memobird server returns a malformed response, the process crashes. We should wrap `JSON.parse` around try catch block and properly rejected that Promise, otherwise process got unexpected quit.

**Comment by sherluok** [comment]
Thank you for posting this issue, I fixed it in the newest version.

**Comment by evianzhow** [comment]
@sherluok According to https://github.com/request/request usage. It's better to apply a default value `{}` to `response`. Official demo said: `response && response.statusCode`.
https://github.com/sherluok/memobird/blob/f94555519c4ca982f9e683dec83637cd21f89c6a/src/index.js#L38

**Comment by sherluok** [comment]
@EvianZhow Yes, the original code handled  the`error` and `response` value in wrong order. I think the `response` value will be null only when an `error` happens, so if we check the `error` value first, there is no need to give the `response` a default value. But I did it anyway in case of i am wrong. Please check the version 0.0.9.
